title: "[QA] 问答 / Q&A "
body:
  - type: textarea
    attributes:
      label: 问题 / Question
      description: 直接描述你遇到的问题或想问的点（越具体越好）/ Describe your question (the more specific, the better).
      placeholder: |
        我在……时遇到……
        期望……，但实际……
    validations:
      required: true

  - type: textarea
    attributes:
      label: 已尝试 / What you tried
      description: 你已经试过哪些方法/步骤？结果如何？/ What have you tried and what happened?
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    attributes:
      label: 版本/环境（可选） / Version & environment (optional)
      description: 例如 OS、App 版本、Node/Python 等 / e.g., OS, app version, Node/Python, etc.
      placeholder: |
        - OS：
        - App 版本 / App version：
        - 其它 / Others：
    validations:
      required: false
 